# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
     build:
          working_directory: ~/repo
          docker:
               # Use the same Docker base as the project
          - image: python:3.7.3-stretch

          steps:
               - checkout
               - restore_cache:
                    key: v1-dependencies-{{ checksum "requirements.txt" }}
           

               - run:
                    name: install dependencies
                    command: |
                    command: python3 -m venv venv
                    command: . venv/bin/activate
                    command: make install
                    # Install hadolint
                    command: wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                    command: chmod +x /bin/hadolint
               - save_cache:
                    paths:
                    - ./venv
                    key: v1-dependencies-{{ checksum "requirements.txt" }}

               # run lint!
               - run:
                    name: run lint
                    command: |
                    command: . venv/bin/activate
                    command: make lint 
